### ISSUE TITLE
Custom badge method is broken in 8.3

### ISSUE THREAD

**Issue by drulang** [enryold/UITabBarItem-CustomBadge#4]
Example usage: 

`[tabBarItem setCustomBadgeValue:@"5" withFont:[UIFont systemFontOfSize:10] andFontColor:[UIColor whiteColor] andBackgroundColor:[UIColor greenColor]];`

This line isn't returning the view anymore:
`UIView *v = [self valueForKey:@"view"];`

**Comment by enryold** [comment]
Thank you @drulang, i have to download last SDK to try it out (i'm out from iOS business since 8.1 :) )
